const fs = require('fs');
const path = require('path');

const IMPORTERS_JS = path.resolve('api/_data/importersData.js');
const rawContent = fs.readFileSync(IMPORTERS_JS, 'utf8');
const impMatch = rawContent.match(/export const IMPORTERS = (\[[\s\S]*?\]);/);
if (!impMatch) {
  console.error('FAIL: Could not parse IMPORTERS from api/_data/importersData.js');
  process.exit(1);
}
const baselineImporters = JSON.parse(impMatch[1]);

if (baselineImporters.length !== 612) {
  console.error(`FAIL: Expected 612 baseline importers, got ${baselineImporters.length}`);
  process.exit(1);
}

const newRecords = [
  // ── 1. Saudi Arabia (GCC) ───────────────────────────────────
  {
    id: 613,
    leadId: 'AAF-IMP-0901',
    name: 'Esnad Food Company Ltd',
    companyName: 'Esnad Food Company Ltd',
    country: 'Saudi Arabia',
    region: 'Middle East',
    state: 'Makkah Province',
    city: 'Jeddah',
    location: 'Jeddah, Saudi Arabia',
    address: 'Jeddah Industrial City 3, 21446, Saudi Arabia',
    website: 'https://esnadfood.com',
    email: 'Not Available',
    phone: '+966 920008693',
    whatsapp: 'Not Available',
    contactPerson: 'Procurement Department',
    jobTitle: 'Spice & Seasoning Procurement Manager',
    designation: 'Spice & Seasoning Procurement Manager',
    businessType: 'Seasoning & Spice Manufacturer',
    industry: 'Spices, Seasonings & Culinary Blends',
    products: 'Moringa Powder, Red Onion Powder, Seasoning Powders, Culinary Spices',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'UNVERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Saudi Food & Drug Authority / Gulfood Exhibitor Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Saudi Arabia',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Major Saudi manufacturer of spice blends, dehydrated seasoning powders, and culinary ingredients in Jeddah Industrial City 3. Strong buyer profile for bulk dehydrated red onion powder and functional botanical ingredients.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 614,
    leadId: 'AAF-IMP-0902',
    name: 'Almunajem Foods',
    companyName: 'Almunajem Foods',
    country: 'Saudi Arabia',
    region: 'Middle East',
    state: 'Riyadh Province',
    city: 'Riyadh',
    location: 'Riyadh, Saudi Arabia',
    address: 'P.O. Box 1544, Riyadh 11441, Saudi Arabia',
    website: 'https://almunajemfoods.com',
    email: 'IR@almunajemfoods.com',
    phone: '+966 11 475 5555',
    whatsapp: 'Not Available',
    contactPerson: 'Commercial Procurement Desk',
    jobTitle: 'Food Ingredients Sourcing Director',
    designation: 'Food Ingredients Sourcing Director',
    businessType: 'Food Ingredient Importer & Wholesale Distributor',
    industry: 'Food Ingredients, Spices & Foodservice Distribution',
    products: 'Dehydrated Onion Powder, Botanical Health Ingredients, Bulk Spices',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Saudi Chamber of Commerce / Riyadh Food Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Saudi Arabia',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Publicly traded Saudi food group (Tadawul: 4162). Major importer and national distributor supplying wholesale, industrial food processing, and HORECA sectors across the Kingdom.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 615,
    leadId: 'AAF-IMP-0903',
    name: 'Binzagr Company',
    companyName: 'Binzagr Company',
    country: 'Saudi Arabia',
    region: 'Middle East',
    state: 'Makkah Province',
    city: 'Jeddah',
    location: 'Jeddah, Saudi Arabia',
    address: 'P.O. Box 54, Jeddah 21411, Saudi Arabia',
    website: 'http://www.binzagr.com.sa',
    email: 'info@binzagr.com.sa',
    phone: '+966 12 216 8000',
    whatsapp: 'Not Available',
    contactPerson: 'Supply Chain & Sourcing Department',
    jobTitle: 'Import & Commodity Procurement Manager',
    designation: 'Import & Commodity Procurement Manager',
    businessType: 'Wholesale Food Distributor & Importer',
    industry: 'Food Distribution & Agricultural Commodities',
    products: 'Agricultural Commodities, Dehydrated Vegetables, Seasonings',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Jeddah Chamber of Commerce / FMCG Trade Registry',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Saudi Arabia',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'One of the largest trading and FMCG distribution conglomerates in Saudi Arabia (founded 1881). Extensive nationwide temperature-controlled warehousing and bulk commodity import capabilities.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 2. Qatar (GCC) ──────────────────────────────────────────
  {
    id: 616,
    leadId: 'AAF-IMP-0904',
    name: 'Safeco Trading Co.',
    companyName: 'Safeco Trading Co.',
    country: 'Qatar',
    region: 'Middle East',
    state: 'Doha',
    city: 'Doha',
    location: 'Doha, Qatar',
    address: 'Industrial Area, Zone 57, Street #1, Gate #168, Doha, Qatar',
    website: 'https://safecotrading.com',
    email: 'info@safecotrading.com',
    phone: '+974 4460 2005',
    whatsapp: '+974 7442 0056',
    contactPerson: 'Import Procurement Division',
    jobTitle: 'Bulk Spice & Food Commodity Buyer',
    designation: 'Bulk Spice & Food Commodity Buyer',
    businessType: 'Spice Importer & Food Ingredient Distributor',
    industry: 'Spices, Seasonings, Pulses & Food Commodities',
    products: 'Moringa Powder, Red Onion Powder, Ground Spices, Masalas',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Qatar Chamber of Commerce / Doha B2B Trade Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Qatar',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Established 2007 in Doha Industrial Area. Premier importer, processor, and distributor of spices, seasonings, and dry food ingredients for Qatar wholesale and HORECA markets.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 617,
    leadId: 'AAF-IMP-0905',
    name: 'Asyan Trading Company',
    companyName: 'Asyan Trading Company',
    country: 'Qatar',
    region: 'Middle East',
    state: 'Al Wakrah',
    city: 'Doha',
    location: 'Doha, Qatar',
    address: 'Building No. 9, Street No. 3133, Zone 91, Birkat Al-Awamer, Doha, Qatar',
    website: 'https://www.asyantradingqa.com',
    email: 'info@asyantradingqa.com',
    phone: '+974 4469 3172',
    whatsapp: 'Not Available',
    contactPerson: 'Sourcing Team',
    jobTitle: 'Procurement Specialist',
    designation: 'Procurement Specialist',
    businessType: 'Food Ingredient Importer & Distributor',
    industry: 'Spices, Herbs, Pulses & Agricultural Foodstuffs',
    products: 'Agricultural Spices, Herbs, Vegetable Powders, Pulses',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'UNVERIFIED',
    priority: 'MEDIUM',
    outreachStatus: 'NEW',
    leadScore: 85,
    leadGrade: 'A',
    source: 'Qatar Financial Centre / Ministry of Commerce & Industry Qatar',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Qatar',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Logistics and distribution hub in Birkat Al-Awamer, Doha. Active importer of bulk herbs, whole and powdered spices, and agricultural food ingredients.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 618,
    leadId: 'AAF-IMP-0906',
    name: 'Kerala Food Centre WLL',
    companyName: 'Kerala Food Centre WLL',
    country: 'Qatar',
    region: 'Middle East',
    state: 'Doha',
    city: 'Doha',
    location: 'Doha, Qatar',
    address: 'Street 37, Gate 52, Industrial Area, P.O. Box 2867, Doha, Qatar',
    website: 'http://kfcdoha.com',
    email: 'purchase@kfcdoha.com',
    phone: '+974 4460 3103',
    whatsapp: 'Not Available',
    contactPerson: 'Purchase Department',
    jobTitle: 'Head of Purchasing & Import Logistics',
    designation: 'Head of Purchasing & Import Logistics',
    businessType: 'Food Importer & Wholesale Distributor',
    industry: 'Dry Food Commodities, Spices & Agro Products',
    products: 'Moringa Powder, Red Onion Powder, Spices, Dry Foodstuffs',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Qatar Commercial Companies Directory / Doha Industrial Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Qatar',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Established in 1989. Major direct importer and wholesale distributor of bulk agro commodities, spices, and dried ingredients operating from Doha Industrial Area.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 3. Oman (GCC) ───────────────────────────────────────────
  {
    id: 619,
    leadId: 'AAF-IMP-0907',
    name: 'Assarain Food Products LLC',
    companyName: 'Assarain Food Products LLC',
    country: 'Oman',
    region: 'Middle East',
    state: 'Muscat Governorate',
    city: 'Muscat',
    location: 'Muscat, Oman',
    address: 'Al Khuwair, Building No. 5251, Way No. 2748, P.O. Box 1475, PC 112, Ruwi, Sultanate of Oman',
    website: 'https://assarainfoods.com',
    email: 'business@assarain.com',
    phone: '+968 2469 8162',
    whatsapp: 'Not Available',
    contactPerson: 'Commercial Procurement Unit',
    jobTitle: 'FMCG & Food Ingredient Sourcing Manager',
    designation: 'FMCG & Food Ingredient Sourcing Manager',
    businessType: 'Food Ingredient Importer & FMCG Distributor',
    industry: 'Food Commodities, Ingredients & Foodservice Supply',
    products: 'Food Ingredients, Agricultural Foodstuffs, Dehydrated Products',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Oman Chamber of Commerce & Industry / Muscat Trade Register',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Oman',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Established in 1975, subsidiary of the Assarain Group. Operates nationwide sales, cold storage, and ambient distribution for food ingredients and FMCG across the Sultanate.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 620,
    leadId: 'AAF-IMP-0908',
    name: 'Enhance Oman',
    companyName: 'Enhance Oman',
    country: 'Oman',
    region: 'Middle East',
    state: 'Muscat Governorate',
    city: 'Muscat',
    location: 'Muscat, Oman',
    address: 'Towell Group Head Office, Entrance 1, 2nd Floor, Azaiba, P.O. Box 1811, PC 130, Muscat, Sultanate of Oman',
    website: 'https://www.enhance-group.com',
    email: 'info@enhance-group.com',
    phone: '+968 2452 6333',
    whatsapp: 'Not Available',
    contactPerson: 'Brand & Sourcing Directorate',
    jobTitle: 'Senior Purchasing & Supply Chain Manager',
    designation: 'Senior Purchasing & Supply Chain Manager',
    businessType: 'Wholesale Food Distributor & Importer',
    industry: 'Foodservice Ingredients & Agricultural FMCG',
    products: 'Culinary Ingredients, Seasonings, Spices, Foodservice Raw Materials',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Oman Ministry of Commerce, Industry and Investment Promotion',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Oman',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Operating as Matrah Cold Stores LLC under W.J. Towell Group. Largest FMCG and foodservice distributor in Oman with extensive institutional distribution infrastructure.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 621,
    leadId: 'AAF-IMP-0909',
    name: 'Oman Foodstuff Factory LLC',
    companyName: 'Oman Foodstuff Factory LLC',
    country: 'Oman',
    region: 'Middle East',
    state: 'Muscat Governorate',
    city: 'Muscat',
    location: 'Muscat, Oman',
    address: 'P.O. Box 88, Rusayl Industrial Area, PC 124, Muscat, Sultanate of Oman',
    website: 'https://www.almudhish.com',
    email: 'info@almudhish.com',
    phone: '+968 2444 6480',
    whatsapp: 'Not Available',
    contactPerson: 'Factory Sourcing & Materials Dept',
    jobTitle: 'Raw Material Procurement Head',
    designation: 'Raw Material Procurement Head',
    businessType: 'Food Manufacturer & Seasoning Processor',
    industry: 'Snack Foods, Seasonings & Packaged Ingredients',
    products: 'Moringa Powder, Red Onion Powder, Snack Seasonings, Dehydrated Ingredients',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Public Establishment for Industrial Estates (Madayn Oman)',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Oman',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Makers of Al Mudhish food products. Major industrial processing plant in Rusayl Industrial City requiring steady container-load imports of onion powder and seasoning powders.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 4. Kuwait (GCC) ─────────────────────────────────────────
  {
    id: 622,
    leadId: 'AAF-IMP-0910',
    name: 'Ahlia Group Co.',
    companyName: 'Ahlia Group Co.',
    country: 'Kuwait',
    region: 'Middle East',
    state: 'Al Farwaniyah Governorate',
    city: 'Kuwait City',
    location: 'Kuwait City, Kuwait',
    address: 'Block 1, Building 154, Ardiya Industrial Area, P.O. Box 2280, Safat 13023, Kuwait',
    website: 'https://ahliafood.com',
    email: 'info@ahliafood.com',
    phone: '+965 2434 0262',
    whatsapp: 'Not Available',
    contactPerson: 'Sourcing & Quality Department',
    jobTitle: 'Import Procurement Director',
    designation: 'Import Procurement Director',
    businessType: 'Spice Importer & Food Manufacturer',
    industry: 'Spices, Seasonings, Herbs & Bulk Foodstuffs',
    products: 'Moringa Powder, Red Onion Powder, Spices, Culinary Herbs, Pulses',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Kuwait Chamber of Commerce & Industry / Industrial Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Kuwait',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Established in 1996 in Ardiya Industrial Area. Kuwait market leader in spice processing, cleaning, packaging, and commercial distribution of herbs, seasonings, and pulses.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 623,
    leadId: 'AAF-IMP-0911',
    name: 'Arena Foods',
    companyName: 'Arena Foods',
    country: 'Kuwait',
    region: 'Middle East',
    state: 'Al Asimah Governorate',
    city: 'Kuwait City',
    location: 'Kuwait City, Kuwait',
    address: 'Shuwaikh Industrial Area 3, New Wholesale Market, Block A, Street 70, Kuwait',
    website: 'https://arenafoodskw.com',
    email: 'Sales@arenafoodskw.com',
    phone: '+965 5030 1566',
    whatsapp: '+965 5030 1566',
    contactPerson: 'Wholesale Sourcing Desk',
    jobTitle: 'Bulk Commodity Sourcing Manager',
    designation: 'Bulk Commodity Sourcing Manager',
    businessType: 'Food Wholesaler & Spice Distributor',
    industry: 'Spices, Seeds, Pulses & Foodservice Sourcing',
    products: 'Bulk Spices, Dehydrated Onion Powder, Botanical Seeds, Seasonings',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'UNVERIFIED',
    priority: 'MEDIUM',
    outreachStatus: 'NEW',
    leadScore: 85,
    leadGrade: 'A',
    source: 'Kuwait Ministry of Commerce / Shuwaikh Wholesale Market Registry',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Kuwait',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Located in Shuwaikh Wholesale Food Market. Supplies 25kg bulk sacks of spices, seasoning ingredients, and dry commodities to Kuwaiti restaurants, catering, and packaging plants.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 624,
    leadId: 'AAF-IMP-0912',
    name: 'Mezzan Holding Co.',
    companyName: 'Mezzan Holding Co.',
    country: 'Kuwait',
    region: 'Middle East',
    state: 'Mubarak Al-Kabeer Governorate',
    city: 'Kuwait City',
    location: 'Kuwait City, Kuwait',
    address: 'Sabhan Industrial Area, Block 11, Plot 221, P.O. Box 124, Safat 13002, Kuwait',
    website: 'https://www.mezzan.com',
    email: 'bd@mezzan.com',
    phone: '+965 2228 6444',
    whatsapp: 'Not Available',
    contactPerson: 'Business Development & Ingredients Procurement',
    jobTitle: 'Group Procurement Director',
    designation: 'Group Procurement Director',
    businessType: 'Food Manufacturer & Large-Scale Distributor',
    industry: 'Food Processing, FMCG Manufacturing & Distribution',
    products: 'Dehydrated Onion Flakes & Powder, Natural Food Additives, Botanical Ingredients',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Kuwait Stock Exchange Boursa Kuwait / Food Sector Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Kuwait',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Public company listed on Boursa Kuwait (Ticker: MEZZAN). Operates large-scale food manufacturing plants across the GCC. High-volume buyer of dehydrated vegetable powders and seasoning ingredients.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 5. South Korea (East Asia) ──────────────────────────────
  {
    id: 625,
    leadId: 'AAF-IMP-0913',
    name: 'BTC Corporation',
    companyName: 'BTC Corporation',
    country: 'South Korea',
    region: 'Asia Pacific',
    state: 'Seoul Capital Area',
    city: 'Seoul',
    location: 'Seoul, South Korea',
    address: '#302, Sungmun Bldg., 2636 Nambusunhwan-ro, Seocho-gu, Seoul, Republic of Korea',
    website: 'https://btcbio.com',
    email: 'info@btcbio.com',
    phone: '+82 2 6404 0190',
    whatsapp: 'Not Available',
    contactPerson: 'Nutraceutical Ingredients Team',
    jobTitle: 'Botanical Raw Materials Sourcing Lead',
    designation: 'Botanical Raw Materials Sourcing Lead',
    businessType: 'Nutraceutical & Botanical Extract Importer',
    industry: 'Functional Food Ingredients & Herbal Extracts',
    products: 'Moringa Powder, Botanical Extracts, Functional Nutrition Powders',
    moringaInterest: 'High',
    redOnionInterest: 'Potential',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Korea Health Functional Food Association (KHSA) / TradeKorea',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'South Korea',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Korean bio-ingredient and nutraceutical leader with R&D labs in Gwacheon and manufacturing in Iksan/Osong. Imports botanical superfoods, functional herbal powders, and health ingredients.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 626,
    leadId: 'AAF-IMP-0914',
    name: 'VIXXOL Corporation',
    companyName: 'VIXXOL Corporation',
    country: 'South Korea',
    region: 'Asia Pacific',
    state: 'Gyeonggi-do',
    city: 'Gunpo-si',
    location: 'Gunpo-si, South Korea',
    address: '7th Floor, 196, LS-ro, Gunpo-si, Gyeonggi-do, 15807, Republic of Korea',
    website: 'http://www.vixxol.com',
    email: 'Not Available',
    phone: '+82 31 492 1541',
    whatsapp: 'Not Available',
    contactPerson: 'Food Ingredients Division',
    jobTitle: 'Senior Raw Materials Buyer',
    designation: 'Senior Raw Materials Buyer',
    businessType: 'Food Ingredient Importer & Distributor',
    industry: 'Food Ingredients, Functional Additives & Premixes',
    products: 'Dehydrated Onion Powder, Functional Food Raw Materials, Premixes',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'UNVERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 85,
    leadGrade: 'A',
    source: 'Korea Food Industry Association (KFIA) / KOTRA Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'South Korea',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Founded in 1976. Major Korean distributor of food additives, functional ingredients, and industrial seasoning premixes. Supplies major Korean food processing corporations.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 627,
    leadId: 'AAF-IMP-0915',
    name: 'Hyangrim Corporation',
    companyName: 'Hyangrim Corporation',
    country: 'South Korea',
    region: 'Asia Pacific',
    state: 'Seoul Capital Area',
    city: 'Seoul',
    location: 'Seoul, South Korea',
    address: '924, C, Beobwon-ro 11-gil 7, Songpa-gu, Seoul 05836, Republic of Korea',
    website: 'http://www.hyangrim.co.kr',
    email: 'Not Available',
    phone: '+82 2 574 8010',
    whatsapp: 'Not Available',
    contactPerson: 'Global Ingredients Sourcing Dept',
    jobTitle: 'Import Sourcing Manager',
    designation: 'Import Sourcing Manager',
    businessType: 'Food Ingredient Importer & Distributor',
    industry: 'Natural Raw Materials, Flavors & Functional Extracts',
    products: 'Moringa Powder, Natural Vegetable Extracts, Botanical Powders',
    moringaInterest: 'High',
    redOnionInterest: 'Potential',
    verificationStatus: 'UNVERIFIED',
    priority: 'MEDIUM',
    outreachStatus: 'NEW',
    leadScore: 85,
    leadGrade: 'A',
    source: 'Korea International Trade Association (KITA) / Seoul B2B Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'South Korea',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Established in 1987 in Songpa-gu, Seoul. Imports and distributes natural raw materials, botanical plant extracts, and functional ingredients from over 20 countries.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 6. Vietnam (Southeast Asia) ─────────────────────────────
  {
    id: 628,
    leadId: 'AAF-IMP-0916',
    name: 'Dh Foods Joint Stock Company',
    companyName: 'Dh Foods Joint Stock Company',
    country: 'Vietnam',
    region: 'Asia Pacific',
    state: 'Ho Chi Minh',
    city: 'Ho Chi Minh City',
    location: 'Ho Chi Minh City, Vietnam',
    address: '9th Floor, 728-730 Vo Van Kiet, Cho Quan Ward, District 5, Ho Chi Minh City, Vietnam',
    website: 'https://www.dhfoods.com.vn',
    email: 'purchase@dhfoods.com.vn',
    phone: '+84 28 3922 5940',
    whatsapp: 'Not Available',
    contactPerson: 'Purchasing Department',
    jobTitle: 'Raw Material Procurement Manager',
    designation: 'Raw Material Procurement Manager',
    businessType: 'Seasoning & Spice Manufacturer',
    industry: 'Natural Spices, Specialty Seasonings & Food Blends',
    products: 'Moringa Powder, Red Onion Powder, Spices, Specialty Seasonings',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Vietnam Food Association (VFA) / Food Ingredients Vietnam',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Vietnam',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Nationally recognized Vietnamese spice and specialty seasoning producer. Emphasizes 100% natural, preservative-free ingredients. High-volume user of dried onion powder and natural botanical ingredients.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 629,
    leadId: 'AAF-IMP-0917',
    name: 'Vianco Ltd.',
    companyName: 'Vianco Ltd.',
    country: 'Vietnam',
    region: 'Asia Pacific',
    state: 'Ho Chi Minh',
    city: 'Ho Chi Minh City',
    location: 'Ho Chi Minh City, Vietnam',
    address: '451/5 Nguyen Trai St., Ward 7, District 5, Ho Chi Minh City, Vietnam',
    website: 'https://giavivietan.com',
    email: 'info@giavivietan.com',
    phone: '+84 28 3923 6265',
    whatsapp: '+84 901 840 808',
    contactPerson: 'Materials & Sourcing Division',
    jobTitle: 'Commodity Procurement Head',
    designation: 'Commodity Procurement Head',
    businessType: 'Spice & Seasoning Manufacturer',
    industry: 'Traditional Spices, Curry Powders & Dehydrated Seasonings',
    products: 'Red Onion Powder, Curry Seasonings, Spices, Herbal Powders',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Vietnam Chamber of Commerce and Industry (VCCI) / HCMC Yellow Pages',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Vietnam',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Operating since 1958 (Viet An Fine Food Products). Pioneer of curry and seasoning manufacturing in Vietnam. Imports raw spice materials and dehydrated vegetable powders for domestic and export lines.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 630,
    leadId: 'AAF-IMP-0918',
    name: 'Annam Group',
    companyName: 'Annam Group',
    country: 'Vietnam',
    region: 'Asia Pacific',
    state: 'Ho Chi Minh',
    city: 'Ho Chi Minh City',
    location: 'Ho Chi Minh City, Vietnam',
    address: '41 Thao Dien Street, Thao Dien Ward, Thu Duc City, Ho Chi Minh City, Vietnam',
    website: 'https://annam-group.com',
    email: 'vietnam@annam-group.com',
    phone: '+84 28 3512 6400',
    whatsapp: 'Not Available',
    contactPerson: 'Food Service & Sourcing Division',
    jobTitle: 'Import & Supply Chain Director',
    designation: 'Import & Supply Chain Director',
    businessType: 'Food Importer & National Distributor',
    industry: 'Premium Food Distribution, Gourmet Ingredients & HORECA',
    products: 'Organic Ingredients, Moringa Powder, Gourmet Spices, Seasonings',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'EuroCham Vietnam Food & Beverage Sector / HCMC Business Registry',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Vietnam',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Founded in 2000. Premier importer and distributor of international food, beverages, and specialty ingredients serving retail (Annam Gourmet) and high-end foodservice across Vietnam.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 7. Thailand (Southeast Asia) ────────────────────────────
  {
    id: 631,
    leadId: 'AAF-IMP-0919',
    name: 'Nithi Foods Co., Ltd.',
    companyName: 'Nithi Foods Co., Ltd.',
    country: 'Thailand',
    region: 'Asia Pacific',
    state: 'Chiang Mai',
    city: 'Chiang Mai',
    location: 'Chiang Mai, Thailand',
    address: '21/6 Moo 2, Chiang Mai-Hod Rd., Banklang, Sanpatong, Chiang Mai 50120, Thailand',
    website: 'https://www.nithifoods.co.th',
    email: 'sales@nithifoods.co.th',
    phone: '+66 53 481 484',
    whatsapp: 'Not Available',
    contactPerson: 'Industrial Sales & Procurement',
    jobTitle: 'Raw Material Sourcing Manager',
    designation: 'Raw Material Sourcing Manager',
    businessType: 'Food Manufacturer & Seasoning Specialist',
    industry: 'Dehydrated Spices, Garlic & Onion Powders, Flavor Solutions',
    products: 'Moringa Powder, Red Onion Powder, Dehydrated Garlic, Seasoning Blends',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Department of International Trade Promotion (DITP) Thailand / THAIFEX',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Thailand',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Founded in 1998. Specialized manufacturer and B2B industrial ingredient supplier of dehydrated spices, onion/garlic powders, and custom seasonings for snack and food processing plants.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 632,
    leadId: 'AAF-IMP-0920',
    name: 'A.R.S. Foods Co., Ltd.',
    companyName: 'A.R.S. Foods Co., Ltd.',
    country: 'Thailand',
    region: 'Asia Pacific',
    state: 'Samut Sakhon',
    city: 'Samut Sakhon',
    location: 'Samut Sakhon, Thailand',
    address: '7 Moo 6, Leabklongseewa Road, Khok Krabue, Mueang Samut Sakhon, Samut Sakhon 74000, Thailand',
    website: 'http://www.arsfoods.co.th',
    email: 'Not Available',
    phone: 'Not Available',
    whatsapp: 'Not Available',
    contactPerson: 'Purchasing & Planning',
    jobTitle: 'Ingredient Sourcing Lead',
    designation: 'Ingredient Sourcing Lead',
    businessType: 'Food Manufacturer & Seasoning Importer',
    industry: 'Seasoning Powders, Dehydrated Vegetables & Herbs',
    products: 'Dehydrated Red Onion Powder, Dried Herbs, Seasoning Bases',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'UNVERIFIED',
    priority: 'MEDIUM',
    outreachStatus: 'NEW',
    leadScore: 80,
    leadGrade: 'B',
    source: 'Thai Food Processors Association (TFPA) / Kompass Thailand',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Thailand',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Manufacturer in Samut Sakhon industrial zone specializing in custom seasoning powders and dried vegetable ingredients for noodle, snack, and food manufacturers.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 633,
    leadId: 'AAF-IMP-0921',
    name: 'Multitech Foods Manufacturing Co., Ltd.',
    companyName: 'Multitech Foods Manufacturing Co., Ltd.',
    country: 'Thailand',
    region: 'Asia Pacific',
    state: 'Samut Prakan',
    city: 'Samut Prakan',
    location: 'Samut Prakan, Thailand',
    address: '789 Moo 2, Phraek Sa Mai, Mueang Samut Prakan, Samut Prakan 10280, Thailand',
    website: 'https://www.mtf.co.th',
    email: 'exports@mtf.co.th',
    phone: '+66 2 826 5479',
    whatsapp: '+66 82 792 9242',
    contactPerson: 'Export & Sourcing Operations',
    jobTitle: 'Raw Materials Sourcing Director',
    designation: 'Raw Materials Sourcing Director',
    businessType: 'Food Manufacturer & Ingredient Processor',
    industry: 'Spray Dried Botanicals, Seasoning Powders & Flavors',
    products: 'Moringa Powder, Spray-Dried Botanical Powders, Onion Seasonings',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Board of Investment (BOI) Thailand / Food Ingredients Asia',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Thailand',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Established in 1976 (formerly Inthaco). Major Thai food ingredient processor specializing in spray drying, botanical powder solutions, and industrial seasonings for snack and beverage sectors.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 8. South Africa (Africa) ────────────────────────────────
  {
    id: 634,
    leadId: 'AAF-IMP-0922',
    name: 'Bragan Ingredients',
    companyName: 'Bragan Ingredients',
    country: 'South Africa',
    region: 'Africa',
    state: 'Gauteng',
    city: 'Johannesburg',
    location: 'Johannesburg, South Africa',
    address: 'Unit 4, Malibongwe Industrial Park, Cnr R114 & Malibongwe Drive, Johannesburg, Gauteng 1739, South Africa',
    website: 'https://www.braganingredients.co.za',
    email: 'enquiries@braganingredients.co.za',
    phone: '+27 11 708 0007',
    whatsapp: 'Not Available',
    contactPerson: 'Procurement & Technical Division',
    jobTitle: 'Food Ingredients Product Manager',
    designation: 'Food Ingredients Product Manager',
    businessType: 'Food Ingredient Importer & National Distributor',
    industry: 'Food Additives, Dehydrated Ingredients & Agricultural Raw Materials',
    products: 'Dehydrated Onion Powder, Botanical Health Ingredients, Preservatives',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'South African Association for the Food Science and Technology (SAAFoST)',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'South Africa',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Member of Rolfes Group. Leading South African national importer and distributor of food additives, dehydrated ingredients, and functional raw materials with warehouses in Johannesburg, Durban, and Cape Town.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 635,
    leadId: 'AAF-IMP-0923',
    name: 'Deli Spices (Pty) Ltd',
    companyName: 'Deli Spices (Pty) Ltd',
    country: 'South Africa',
    region: 'Africa',
    state: 'Western Cape',
    city: 'Cape Town',
    location: 'Cape Town, South Africa',
    address: '25 Bertie Avenue, Epping Industria 2, Cape Town 7460, South Africa',
    website: 'https://delispices.co.za',
    email: 'info@delispices.co.za',
    phone: '+27 21 505 2000',
    whatsapp: 'Not Available',
    contactPerson: 'Sourcing & Supply Chain Team',
    jobTitle: 'Head of Spice & Herb Purchasing',
    designation: 'Head of Spice & Herb Purchasing',
    businessType: 'Seasoning & Spice Manufacturer',
    industry: 'Spices, Seasoning Blends, Marinades & Food Ingredients',
    products: 'Moringa Powder, Red Onion Powder, Seasoning Powders, Meat Seasonings',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Cape Chamber of Commerce / South African Spice Industry Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'South Africa',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'One of the leading spice and seasoning blend manufacturers in Southern Africa. Headquartered in Epping Industria, Cape Town, supplying butchery, poultry, and meat processing sectors.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 636,
    leadId: 'AAF-IMP-0924',
    name: 'Cape Foods',
    companyName: 'Cape Foods',
    country: 'South Africa',
    region: 'Africa',
    state: 'Western Cape',
    city: 'Cape Town',
    location: 'Cape Town, South Africa',
    address: '1 Ruby Boulevard, Montague Park, Montague Gardens, 7441, Cape Town, South Africa',
    website: 'https://www.capefoods.co.za',
    email: 'info@capefoods.co.za',
    phone: '+27 21 552 0800',
    whatsapp: 'Not Available',
    contactPerson: 'International Sourcing Desk',
    jobTitle: 'Commodities Procurement Director',
    designation: 'Commodities Procurement Director',
    businessType: 'Spice Manufacturer & Global Importer',
    industry: 'Herbs, Spices, Custom Seasonings & Private Label Blends',
    products: 'Dehydrated Onion Flakes, Organic Spices, Herbal Ingredients',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'South African Department of Trade, Industry and Competition (DTIC)',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'South Africa',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Major South African spice and herb packer and international exporter/importer. Operates custom blending and private labeling facility in Montague Gardens, Cape Town.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 9. Nigeria (West Africa) ────────────────────────────────
  {
    id: 637,
    leadId: 'AAF-IMP-0925',
    name: 'AACE Food Processing & Distribution Ltd',
    companyName: 'AACE Food Processing & Distribution Ltd',
    country: 'Nigeria',
    region: 'Africa',
    state: 'Lagos Corridor / Ogun',
    city: 'Lagos',
    location: 'Lagos, Nigeria',
    address: '3 Celak Avenue, Olaotan Bus Stop, Ijoko Road, Sango Ota, Ogun State / Lagos Corridor, Nigeria',
    website: 'https://aacefoods.com',
    email: 'Not Available',
    phone: '+234 707 475 3843',
    whatsapp: 'Not Available',
    contactPerson: 'Raw Materials Purchasing Desk',
    jobTitle: 'Agro Processing Procurement Officer',
    designation: 'Agro Processing Procurement Officer',
    businessType: 'Seasoning & Spice Manufacturer',
    industry: 'Indigenous Spices, Seasonings & Fortified Agricultural Foods',
    products: 'Moringa Powder, Red Onion Powder, Garlic Powder, Ginger Powder',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Lagos Chamber of Commerce and Industry (LCCI) / NAFDAC Registered Food Processors',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Nigeria',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Pioneering Nigerian food processor and seasoning manufacturer. Produces natural packaged spice powders, garlic, ginger, and nutritious foods. High compatibility with organic moringa and dehydrated onion powder.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 638,
    leadId: 'AAF-IMP-0926',
    name: 'Erisco Foods Limited',
    companyName: 'Erisco Foods Limited',
    country: 'Nigeria',
    region: 'Africa',
    state: 'Lagos State',
    city: 'Lagos',
    location: 'Lagos, Nigeria',
    address: '2 Oyeleke Street, Oregun, Alausa, Ikeja, Lagos, Nigeria',
    website: 'https://eriscofoodsltd.com.ng',
    email: 'info@eriscofoodsltd.com.ng',
    phone: '+234 813 444 0000',
    whatsapp: 'Not Available',
    contactPerson: 'Industrial Purchasing Directorate',
    jobTitle: 'Head of Raw Material Procurement',
    designation: 'Head of Raw Material Procurement',
    businessType: 'Food Manufacturer & Seasoning Processor',
    industry: 'Seasoning Cubes, Tomato Processing & Packaged Seasonings',
    products: 'Onion Seasoning Powders, Curry Powders, Dehydrated Onion Flakes',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Manufacturers Association of Nigeria (MAN) / Food, Beverage & Tobacco Sectoral Group',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Nigeria',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Major indigenous Nigerian food manufacturer in Ikeja, Lagos. Produces seasoning cubes, curry seasonings, and onion flavor bases. Substantial requirement for bulk dehydrated onion powder.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 639,
    leadId: 'AAF-IMP-0927',
    name: 'Canvest Nigeria Limited',
    companyName: 'Canvest Nigeria Limited',
    country: 'Nigeria',
    region: 'Africa',
    state: 'Lagos State',
    city: 'Lagos',
    location: 'Lagos, Nigeria',
    address: 'No. 3B Eko-Akete Street, off St. Gregory’s Road, S.W. Ikoyi, P.O. Box 51992, Falomo, Lagos, Nigeria',
    website: 'https://canvestgroup.com',
    email: 'info@canvestgroup.com',
    phone: '+234 1 628 2671',
    whatsapp: 'Not Available',
    contactPerson: 'Import Operations Team',
    jobTitle: 'Commercial Import Manager',
    designation: 'Commercial Import Manager',
    businessType: 'Food Importer & National Distributor',
    industry: 'Imported Food Distribution, Spices & FMCG Brands',
    products: 'Imported Spices, Seasonings, Food Ingredients, Chili Products',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'UNVERIFIED',
    priority: 'MEDIUM',
    outreachStatus: 'NEW',
    leadScore: 85,
    leadGrade: 'A',
    source: 'Nigerian-British Chamber of Commerce / Lagos State Ministry of Commerce',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Nigeria',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Established in 1980 in Ikoyi, Lagos. Longstanding importer and distributor of international spice and seasoning brands, partnered with Dunrobin Foods for local packaging.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },

  // ── 10. Brazil (Latin America) ──────────────────────────────
  {
    id: 640,
    leadId: 'AAF-IMP-0928',
    name: 'Tovani Benzaquen Ingredientes',
    companyName: 'Tovani Benzaquen Ingredientes',
    country: 'Brazil',
    region: 'Latin America',
    state: 'São Paulo',
    city: 'São Paulo',
    location: 'São Paulo, Brazil',
    address: 'Avenida Angélica, 2220, Consolação, São Paulo - SP, 01228-200, Brazil',
    website: 'https://tovani.com.br',
    email: 'suporte.br@barentz.com',
    phone: '+55 11 2974 7474',
    whatsapp: 'Not Available',
    contactPerson: 'Divisão de Nutrição Humana e Ingredientes',
    jobTitle: 'Diretor de Suprimentos & Importação',
    designation: 'Diretor de Suprimentos & Importação',
    businessType: 'Food Ingredient & Nutraceutical Importer/Distributor',
    industry: 'Nutraceuticals, Functional Plant Extracts & Food Ingredients',
    products: 'Moringa Powder, Botanical Extracts, Functional Ingredients, Natural Colors',
    moringaInterest: 'High',
    redOnionInterest: 'Potential',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 95,
    leadGrade: 'A',
    source: 'Associação Brasileira da Indústria de Ingredientes e Alimentos para Fins Especiais (ABIFISA)',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Brazil',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Founded in 1992, part of the Barentz global life science group. Leading Brazilian distributor of functional food, nutraceutical, and natural plant ingredients with specialized application laboratories in São Paulo.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 641,
    leadId: 'AAF-IMP-0929',
    name: 'Vogler Ingredients',
    companyName: 'Vogler Ingredients',
    country: 'Brazil',
    region: 'Latin America',
    state: 'São Paulo',
    city: 'São Bernardo do Campo',
    location: 'São Bernardo do Campo, Brazil',
    address: 'Estrada Fukutaro Yida, 1155/1173, Cooperativa, São Bernardo do Campo - SP, 09852-060, Brazil',
    website: 'https://vogler.com.br',
    email: 'mkt.vogler@vogler.com.br',
    phone: '+55 11 4393 4400',
    whatsapp: 'Not Available',
    contactPerson: 'Departamento de Compras e Importação',
    jobTitle: 'Gerente de Compras Internacionais',
    designation: 'Gerente de Compras Internacionais',
    businessType: 'Food Ingredient Importer & Specialty Distributor',
    industry: 'Specialty Ingredients, Plant Extracts & Nutrition Solutions',
    products: 'Dehydrated Onion Powder, Botanical Powders, Food Seasonings',
    moringaInterest: 'High',
    redOnionInterest: 'High',
    verificationStatus: 'VERIFIED',
    priority: 'HIGH',
    outreachStatus: 'NEW',
    leadScore: 90,
    leadGrade: 'A',
    source: 'Associação Brasileira das Indústrias da Alimentação (ABIA) / São Paulo Trade Registry',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Brazil',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'An Azelis group company. One of the top ingredient distribution enterprises in Brazil supplying food, nutrition, and beverage manufacturers with high-purity botanical and dehydrated ingredients.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  },
  {
    id: 642,
    leadId: 'AAF-IMP-0930',
    name: 'MasterSense Ingredientes',
    companyName: 'MasterSense Ingredientes',
    country: 'Brazil',
    region: 'Latin America',
    state: 'São Paulo',
    city: 'Jundiaí',
    location: 'Jundiaí, Brazil',
    address: 'Rodovia Vice-Prefeito Hermenegildo Tonolli, Distrito Industrial, Jundiaí - SP, 13213-086, Brazil',
    website: 'https://www.mastersense.com',
    email: 'vendas@mastersense.com',
    phone: '+55 11 3109 3100',
    whatsapp: 'Not Available',
    contactPerson: 'Equipe de Sourcing Global',
    jobTitle: 'Especialista em Ingredientes Alimentícios',
    designation: 'Especialista em Ingredientes Alimentícios',
    businessType: 'Food Ingredient Importer & Solutions Provider',
    industry: 'Food Flavors, Functional Ingredients & Seasonings',
    products: 'Dehydrated Vegetable Powders, Natural Seasoning Bases, Botanicals',
    moringaInterest: 'Potential',
    redOnionInterest: 'High',
    verificationStatus: 'UNVERIFIED',
    priority: 'MEDIUM',
    outreachStatus: 'NEW',
    leadScore: 85,
    leadGrade: 'A',
    source: 'Food Ingredients South America (FiSA) / FIESP São Paulo Directory',
    sourceFile: 'leads_research_country_coverage_2026.json',
    sourceSheet: 'Brazil',
    sourceType: 'B2B Trade Research & Verified Commercial Registry',
    notes: 'Based in Jundiaí (São Paulo metropolitan area). Specializes in innovative food ingredients, aromas, and dehydrated vegetable bases for Brazilian food and beverage manufacturers.',
    googleMapsUrl: '',
    linkedinUrl: '',
    facebookUrl: '',
    instagramUrl: '',
    importedAt: '2026-10-03T00:00:00.000Z'
  }
];

console.log(`Appending ${newRecords.length} newly researched records to 612 baseline records...`);
const combinedImporters = [...baselineImporters, ...newRecords];
console.log(`Total importers will be: ${combinedImporters.length}`);

// Write formatted JS file
const header = `// ============================================================
// AVANI AGRO FOODS — Global Importers Master Dataset
// Serverless Data Store (Protected by Master Password Gate)
// Authoritative Record Count: ${combinedImporters.length}
// 612 Authoritative Baseline + 30 Researched Country-Coverage Records
// 21 Canonical Target Countries 100% Represented
// ============================================================

export const IMPORTERS = ${JSON.stringify(combinedImporters, null, 2)};
`;

fs.writeFileSync(IMPORTERS_JS, header, 'utf8');
console.log(`SUCCESS: Written ${combinedImporters.length} records to ${IMPORTERS_JS}`);
